//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdict2db.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdict2db.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info:.
        /// </summary>
        internal static string AdditionalInfoText {
            get {
                return ResourceManager.GetString("AdditionalInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddTableHS {
            get {
                object obj = ResourceManager.GetObject("AddTableHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:\t\t.
        /// </summary>
        internal static string AmountText {
            get {
                return ResourceManager.GetString("AmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdict2db.
        /// </summary>
        internal static string ApplicationCaption {
            get {
                return ResourceManager.GetString("ApplicationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not finished. Do you want to keep partial results?.
        /// </summary>
        internal static string CancelMessageQuestion {
            get {
                return ResourceManager.GetString("CancelMessageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress:\t\t.
        /// </summary>
        internal static string CompressText {
            get {
                return ResourceManager.GetString("CompressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is closed.
        /// </summary>
        internal static string ConnectionClosedText {
            get {
                return ResourceManager.GetString("ConnectionClosedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is opened.
        /// </summary>
        internal static string ConnectionOpenedText {
            get {
                return ResourceManager.GetString("ConnectionOpenedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string:.
        /// </summary>
        internal static string ConnectionStringText {
            get {
                return ResourceManager.GetString("ConnectionStringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright length:\t.
        /// </summary>
        internal static string CopyrightLengthText {
            get {
                return ResourceManager.GetString("CopyrightLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating DB table.
        /// </summary>
        internal static string CreateDataTableText {
            get {
                return ResourceManager.GetString("CreateDataTableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table index is created.
        /// </summary>
        internal static string CreateTableIndexText {
            get {
                return ResourceManager.GetString("CreateTableIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table is created.
        /// </summary>
        internal static string CreateTableText {
            get {
                return ResourceManager.GetString("CreateTableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dct.
        /// </summary>
        internal static string DctExtensionText {
            get {
                return ResourceManager.GetString("DctExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No header info..
        /// </summary>
        internal static string DefaultHeaderInfoText {
            get {
                return ResourceManager.GetString("DefaultHeaderInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old table is deleted.
        /// </summary>
        internal static string DeleteTableText {
            get {
                return ResourceManager.GetString("DeleteTableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditInformationHS {
            get {
                object obj = ResourceManager.GetObject("EditInformationHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary is empty..
        /// </summary>
        internal static string EmptyDictionaryText {
            get {
                return ResourceManager.GetString("EmptyDictionaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not be empty..
        /// </summary>
        internal static string EmptyStringText {
            get {
                return ResourceManager.GetString("EmptyStringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist..
        /// </summary>
        internal static string FileDoesNotExistText {
            get {
                return ResourceManager.GetString("FileDoesNotExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error was occured while pasing file..
        /// </summary>
        internal static string FileParsingErrorText {
            get {
                return ResourceManager.GetString("FileParsingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving dictionary to database table. Please wait....
        /// </summary>
        internal static string FillDataText {
            get {
                return ResourceManager.GetString("FillDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Filter2HS {
            get {
                object obj = ResourceManager.GetObject("Filter2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do  you really want to save only filtered data? For saving whole the data press &apos;No&apos;..
        /// </summary>
        internal static string FilteredDataMessageQuestion {
            get {
                return ResourceManager.GetString("FilteredDataMessageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag_blueHS {
            get {
                object obj = ResourceManager.GetObject("Flag_blueHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (see tooltip for additional info).
        /// </summary>
        internal static string HeaderInfoAdditionalText {
            get {
                return ResourceManager.GetString("HeaderInfoAdditionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header  info:.
        /// </summary>
        internal static string HeaderInfoText {
            get {
                return ResourceManager.GetString("HeaderInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index:\t\t\t.
        /// </summary>
        internal static string IndexText {
            get {
                return ResourceManager.GetString("IndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input language:\t\t.
        /// </summary>
        internal static string InputLanguageText {
            get {
                return ResourceManager.GetString("InputLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot lenght:\t\t.
        /// </summary>
        internal static string LenghtShotText {
            get {
                return ResourceManager.GetString("LenghtShotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input only text, digits or symbol &apos;_&apos;..
        /// </summary>
        internal static string MessageValidationQueryStringTableErrorText {
            get {
                return ResourceManager.GetString("MessageValidationQueryStringTableErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset for articles:\t.
        /// </summary>
        internal static string OffsetArticlesText {
            get {
                return ResourceManager.GetString("OffsetArticlesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset for shot index:\t.
        /// </summary>
        internal static string OffsetShotIndexText {
            get {
                return ResourceManager.GetString("OffsetShotIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset for words index:\t.
        /// </summary>
        internal static string OffsetWordsIndexText {
            get {
                return ResourceManager.GetString("OffsetWordsIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was canceled.
        /// </summary>
        internal static string OperationCanceledText {
            get {
                return ResourceManager.GetString("OperationCanceledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary file parsing. Please wait....
        /// </summary>
        internal static string OperationParsingText {
            get {
                return ResourceManager.GetString("OperationParsingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving dictionary to database table. Please wait....
        /// </summary>
        internal static string OperationSqlText {
            get {
                return ResourceManager.GetString("OperationSqlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary file saving. Please wait....
        /// </summary>
        internal static string OperationWritingText {
            get {
                return ResourceManager.GetString("OperationWritingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output language:\t.
        /// </summary>
        internal static string OutputLanguageText {
            get {
                return ResourceManager.GetString("OutputLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature:\t\t.
        /// </summary>
        internal static string SignatureText {
            get {
                return ResourceManager.GetString("SignatureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table for dictionary:.
        /// </summary>
        internal static string TableForDictionaryText {
            get {
                return ResourceManager.GetString("TableForDictionaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data table is not valid..
        /// </summary>
        internal static string TableIsNotValidText {
            get {
                return ResourceManager.GetString("TableIsNotValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary_{0}.
        /// </summary>
        internal static string TableNamePattern {
            get {
                return ResourceManager.GetString("TableNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length:\t\t.
        /// </summary>
        internal static string TitleLengthText {
            get {
                return ResourceManager.GetString("TitleLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string TranslateField {
            get {
                return ResourceManager.GetString("TranslateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt.
        /// </summary>
        internal static string TxtExtensionText {
            get {
                return ResourceManager.GetString("TxtExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version length:\t\t.
        /// </summary>
        internal static string VersionLengthText {
            get {
                return ResourceManager.GetString("VersionLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string WordField {
            get {
                return ResourceManager.GetString("WordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        internal static string ZeroPercentageText {
            get {
                return ResourceManager.GetString("ZeroPercentageText", resourceCulture);
            }
        }
    }
}
